"""Remove selected_tabs column from Event

Revision ID: 0a43986f4f83
Revises: 
Create Date: 2026-05-13 15:33:29.155616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a43986f4f83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('end_datetime',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('selected_tabs')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_tabs', sa.TEXT(), nullable=False))
        batch_op.alter_column('end_datetime',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
