"""Just renaming fk constraints

Revision ID: 376765315ad3
Revises: 0a43986f4f83
Create Date: 2026-05-14 20:16:37.763855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376765315ad3'
down_revision = '0a43986f4f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_event_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event_checklist_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_event_checklist_item_event_id', 'event', ['event_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event_discussion_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_event_discussion_message_event_id', 'event', ['event_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_event_discussion_message_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event_expense', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_event_expense_event_id', 'event', ['event_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event_invite_token', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_event_invite_token_event_id', 'event', ['event_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event_join_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_event_join_request_event_id', 'event', ['event_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_event_join_request_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event_participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_event_participant_event_id', 'event', ['event_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_event_participant_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event_vote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_event_vote_option_option_id', 'event_vote_option', ['option_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_event_vote_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('event_vote_option', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_event_vote_option_event_id', 'event', ['event_id'], ['id'], ondelete='CASCADE')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('event_vote_option', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_vote_option_event_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'])
        batch_op.drop_constraint('uq_event_vote_option_title', type_='unique')
        batch_op.drop_index(batch_op.f('ix_event_vote_option_event_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('event_vote', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_vote_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_event_vote_event_id', type_='foreignkey')
        batch_op.drop_constraint('fk_event_vote_option_option_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'event_vote_option', ['option_id'], ['id'])
        batch_op.drop_constraint('uq_one_vote_per_user_per_event', type_='unique')
        batch_op.drop_index(batch_op.f('ix_event_vote_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_vote_option_id'))
        batch_op.drop_index(batch_op.f('ix_event_vote_event_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('event_id')

    with op.batch_alter_table('event_participant', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_participant_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_event_participant_event_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_constraint('uq_event_participant', type_='unique')
        batch_op.drop_index(batch_op.f('ix_event_participant_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_participant_event_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('rsvp_status')
        batch_op.drop_column('role')

    with op.batch_alter_table('event_join_request', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_join_request_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_event_join_request_event_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'])
        batch_op.drop_constraint('uq_event_join_request', type_='unique')
        batch_op.drop_index(batch_op.f('ix_event_join_request_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_join_request_event_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('event_invite_token', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_invite_token_event_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_event_invite_token_event_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('event_expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_by', sa.VARCHAR(length=80), nullable=True))
        batch_op.drop_constraint('fk_event_expense_paid_by_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_event_expense_event_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_event_expense_paid_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_expense_event_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('paid_by_user_id')

    with op.batch_alter_table('event_discussion_message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_discussion_message_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_event_discussion_message_event_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_event_discussion_message_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_discussion_message_event_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('event_checklist_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_checklist_item_assigned_to_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_event_checklist_item_event_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_event_checklist_item_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_checklist_item_assigned_to_user_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('assigned_to_user_id')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_user_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_index('ix_event_user_start')
        batch_op.drop_index(batch_op.f('ix_event_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_start_datetime'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
